apiVersion: v1
kind: Namespace
metadata:
  name: hello-dev
  labels:
    environment-id: env_d98d8a30-4d85-4893-b66c-a42bd0e19158
    project-id: project_3fee4a6f-b3c8-42c7-9aa8-bc0942e23baa
    project-name: Hello
    environment-name: dev
    organization-id: org_219aede3-da6b-4fe5-8560-fc32e8fb3a28
